[env:attiny85]
platform = atmelavr
framework = arduino

; For many ATtiny85 cores, this board id works directly.
; If your setup differs, run `pio boards atmelavr` and adjust.
board = attiny85

; Arduino Nano running ArduinoISP sketch as programmer
upload_protocol = stk500v1
upload_flags =
    -P
    COM21
    -b
    19200

; Clock target (adjust for your fuse/clock setup)
board_build.f_cpu = 8000000L

monitor_speed = 9600